markup:
  highlight:
    style: "dracula"

module:
  module.hugoVersion:
    min: "0.92.0"
    extended: true

  imports:
    - path: "gitlab.com/writeonlyhugo/hugo-module-bootstrap"
    - path: "gitlab.com/writeonlyhugo/hugo-module-bootstrap-icons"

